name: IPTV-builder
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Builder
        env:
          LIVE_SOURCES_CONF: ${{ vars.LIVE_SOURCES_CONF }}
          VOD_SOURCES_CONF: ${{ vars.VOD_SOURCES_CONF }}
        run: python scripts/builder.py
      - name: Inject Worker URL
        run: sed -i "s|{{CF_WORKER_URL}}|${{ secrets.CF_WORKER_URL }}|g" check.html
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add raw_list.json vod_config.json
          git commit -m "update" || echo "none"
          git push
